name: transformer_training
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - torchaudio==2.7.1+cu118
      - transformers==5.5.0
      - accelerate==1.13.0
      - datasets==4.3.0
      - rouge-score==0.1.2
      - pyyaml==6.0.3
      - tqdm==4.67.3
      - numpy==1.26.4
      - rank-bm25==0.2.2
      - sentencepiece==0.2.1
      - protobuf==4.25.9
      - bitsandbytes==0.49.2