task: "document_reranking"
model_name_or_path:  "allenai/scibert_scivocab_uncased"

# ----- Data -----
train_file:      ../data/scidocs/train.jsonl
validation_file: ../data/scidocs/validation.jsonl
test_file:       ../data/scidocs/test.jsonl

output_dir: "outputs/reranking_scidocs"
max_length: 512

# ----- Training Hyperparameters -----
seed: 42
batch_size: 16
learning_rate: 2e-5
num_epochs: 3
warmup_ratio: 0.1
label_smoothing: 0.1
# max_grad_norm: 0.5
# ----- Logging & Evaluation -----
logging_steps: 50
eval_steps: 200
save_steps: 200

# Mapping cột (nếu cần thiết)
field_map:
  query: "query"
  title: "title"
  abstract: "abstract"
  label: "label"
